### ISSUE TITLE
Custom Tower error on MacOS

### ISSUE THREAD

**Issue by eljeko** [kartchnb/AutoTowersGenerator#110]
I was generating a Custom temp tower but I got this error:

```
Failed to generate "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/tmp/custom_autotower.stl" from "temptower.scad"
Command output was "'<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/tmp' 
is not a directory for output file <HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/tmp/custom_autotower.stl - Skipping"
```

Just to test it I manually created the path 
```
<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/tmp
```
After this workaround it started to work but:

If I use a range with 220 to 230 seems to create the tower always, It crashes with values from >250 to 230 (-5 steps):
```

Traceback (most recent call last):
  File "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/Controllers/TempTowerController.py", line 53, in dialogAccepted
    self._generateCustomTempTower()
  File "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/Controllers/TempTowerController.py", line 126, in _generateCustomTempTower
    self._generateStlCallback(self, towerName, self._openScadFilename, openScadParameters, self.postProcess)
  File "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/AutoTowersGenerator.py", line 439, in _generateStlCallback
    self._importStl(controller, towerName, stlFilePath, postProcessingCallback)
  File "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/AutoTowersGenerator.py", line 447, in _importStl
    self._removeAutoTower()
  File "<HOME>/Library/Application Support/cura/5.6/plugins/AutoTowersGenerator/AutoTowersGenerator/AutoTowersGenerator.py", line 361, in _removeAutoTower
    if Message is not None: Message(message, title=self._pluginName, lifetime=5).show()
  File "UM/Message.py", line 65, in __init__
    self._text = text.replace("\n", "<br>")
AttributeError: 'NoneType' object has no attribute 'replace'
```

Let me know if I can test/help/debug something for you (I know a bit OpenScad)

**Comment by kartchnb** [comment]
Thank you for letting me know there was a problem with the tmp directory. It should always be there, but I've updated my plugin to make sure.

The second issue is a bug that I fixed some time ago but hasn't made its way to the Marketplace.  Fingers crossed, I'll be able to upload a new version (with a whole new set of bugs!) within a few weeks.

Thank you!
