### ISSUE TITLE
Crash when attempting to run plugin

### ISSUE THREAD

**Issue by nallath** [kartchnb/AutoTowersGenerator#2]
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jvankessel/.local/share/cura/5.0/plugins/AutoTowersGenerator/AutoTowersGenerator/AutoTowersGenerator.py", line 278, in <lambda>
2022-03-30 13:24:12,831 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
    openScadThread = threading.Thread(target = lambda: self._openScadInterface.GenerateStl(openScadFilePath, openScadParameters, stlFilePath))
  File "/home/jvankessel/.local/share/cura/5.0/plugins/AutoTowersGenerator/AutoTowersGenerator/OpenScadInterface.py", line 65, in GenerateStl
    subprocess.run(command)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
2022-03-30 13:24:12,832 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2022-03-30 13:24:12,833 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/home/jvankessel/.local/share/cura/5.0/plugins/AutoTowersGenerator/AutoTowersGenerator/FanTowerController.py", line 81, in dialogAccepted
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
2022-03-30 13:24:12,833 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._modelCallback(self._openScadFilename, openScadParameters, self._postProcess)
2022-03-30 13:24:12,834 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/home/jvankessel/.local/share/cura/5.0/plugins/AutoTowersGenerator/AutoTowersGenerator/AutoTowersGenerator.py", line 280, in _modelCallback
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
2022-03-30 13:24:12,834 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     while (openScadThread.isAlive()):
2022-03-30 13:24:12,834 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: AttributeError: 'Thread' object has no attribute 'isAlive'
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openscad'
```

I think you should use is_alive() see: https://docs.python.org/3/library/threading.html#threading.Thread.is_alive. Alternatively look at the suggestion in #1

**Comment by kartchnb** [comment]
In response to issue #1, I changed my code to use the Uranium Job class, which, as you say, solves this issue.

Thank you again!
