### ISSUE TITLE
Error when trying to save project

### ISSUE THREAD

**Issue by kvnper** [kartchnb/AutoTowersGenerator#26]
Using the marketplace version (v2.1.0) so not sure if it's already fixed.

When I go to File -> Save Project and save it, i get the following error message popup and i've also pasted the error log below

![image](https://user-images.githubusercontent.com/47488385/199137301-6771f014-52e0-469c-9a61-f8b086d98b2c.png)

```
2022-11-01 12:09:00,101 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [444]: file:///D:/Program Files/Ultimaker Cura 5.2.1/share/cura/resources/qml/MainWindow/ApplicationMenu.qml:51:9: QML FileMenu: Binding loop detected for property "width"
2022-11-01 12:09:06,650 - DEBUG - [MainThread] LocalFileOutputDevice.LocalFileOutputDevice.requestWrite [133]: Writing to [F:/Downloads/Sliced Files/auto towers profile.3mf]...
2022-11-01 12:09:06,663 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file Untitled: list index out of range
2022-11-01 12:09:06,671 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Traceback (most recent call last):
2022-11-01 12:09:06,672 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Qt\Bindings\OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2022-11-01 12:09:06,672 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     device.requestWrite(nodes, file_name, limit_mimetypes, file_handler, **kwargs)
2022-11-01 12:09:06,673 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "D:\Program Files\Ultimaker Cura 5.2.1\share\uranium\plugins\LocalFileOutputDevice\LocalFileOutputDevice.py", line 148, in requestWrite
2022-11-01 12:09:06,673 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.writeStarted.emit(self)
2022-11-01 12:09:06,674 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:06,674 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:06,675 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:06,675 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:06,676 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 361, in __performEmit
2022-11-01 12:09:06,676 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     signal.emit(*args, **kwargs)
2022-11-01 12:09:06,677 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:06,677 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:06,678 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:06,678 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:06,679 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 357, in __performEmit
2022-11-01 12:09:06,679 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     func(dest, *args, **kwargs)
2022-11-01 12:09:06,680 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Users\Kevin\AppData\Roaming\cura\5.2\plugins\AutoTowersGenerator\AutoTowersGenerator\AutoTowersGenerator.py", line 583, in _postProcess
2022-11-01 12:09:06,680 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     if self._gcodeProcessedMarker not in gcode[0]:
2022-11-01 12:09:06,681 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: IndexError: list index out of range
2022-11-01 12:09:07,176 - INFO - [MainThread] SliceInfoPlugin.SliceInfo._onRequestFinished [295]: SliceInfo sent successfully
2022-11-01 12:09:09,635 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [444]: file:///D:/Program Files/Ultimaker Cura 5.2.1/share/cura/resources/qml/MainWindow/ApplicationMenu.qml:51:9: QML FileMenu: Binding loop detected for property "width"
2022-11-01 12:09:14,934 - DEBUG - [MainThread] LocalFileOutputDevice.LocalFileOutputDevice.requestWrite [133]: Writing to [F:/Downloads/Sliced Files/auto towers profile.3mf]...
2022-11-01 12:09:14,940 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file auto towers profile: list index out of range
2022-11-01 12:09:14,941 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Traceback (most recent call last):
2022-11-01 12:09:14,942 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Qt\Bindings\OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2022-11-01 12:09:14,942 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     device.requestWrite(nodes, file_name, limit_mimetypes, file_handler, **kwargs)
2022-11-01 12:09:14,943 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "D:\Program Files\Ultimaker Cura 5.2.1\share\uranium\plugins\LocalFileOutputDevice\LocalFileOutputDevice.py", line 148, in requestWrite
2022-11-01 12:09:14,943 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.writeStarted.emit(self)
2022-11-01 12:09:14,944 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:14,944 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:14,945 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:14,945 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:14,946 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 361, in __performEmit
2022-11-01 12:09:14,946 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     signal.emit(*args, **kwargs)
2022-11-01 12:09:14,947 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:14,947 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:14,948 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:14,949 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:14,949 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 357, in __performEmit
2022-11-01 12:09:14,950 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     func(dest, *args, **kwargs)
2022-11-01 12:09:14,950 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Users\Kevin\AppData\Roaming\cura\5.2\plugins\AutoTowersGenerator\AutoTowersGenerator\AutoTowersGenerator.py", line 583, in _postProcess
2022-11-01 12:09:14,951 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     if self._gcodeProcessedMarker not in gcode[0]:
2022-11-01 12:09:14,951 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: IndexError: list index out of range
2022-11-01 12:09:15,447 - INFO - [MainThread] SliceInfoPlugin.SliceInfo._onRequestFinished [295]: SliceInfo sent successfully
2022-11-01 12:09:16,717 - DEBUG - [MainThread] cura.AutoSave._onTimeout [64]: Autosaving preferences, instances and profiles took 0.028970718383789062 seconds
2022-11-01 12:09:17,738 - DEBUG - [MainThread] cura.Machines.MachineErrorChecker._rescheduleCheck [164]: New error check scheduled.
2022-11-01 12:09:17,740 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [221]: Error check finished, result = False, time = 0.00s
2022-11-01 12:09:18,126 - INFO - [MainThread] CuraEngineBackend.CuraEngineBackend._createSnapshot [275]: Creating thumbnail image (just before slice)...
2022-11-01 12:09:18,128 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2022-11-01 12:09:18,128 - WARNING - [MainThread] cura.Snapshot.snapshot [68]: Unable to create snapshot as we seem to have an empty buildplate
2022-11-01 12:09:18,129 - INFO - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [290]: Starting to slice...
2022-11-01 12:09:18,130 - WARNING - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [294]: Slice unnecessary, nothing has changed that needs reslicing.
2022-11-01 12:09:22,804 - DEBUG - [MainThread] LocalFileOutputDevice.LocalFileOutputDevice.requestWrite [133]: Writing to [F:/Downloads/Sliced Files/auto towers profile.3mf]...
2022-11-01 12:09:22,810 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file auto towers profile: list index out of range
2022-11-01 12:09:22,811 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Traceback (most recent call last):
2022-11-01 12:09:22,811 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Qt\Bindings\OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2022-11-01 12:09:22,812 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     device.requestWrite(nodes, file_name, limit_mimetypes, file_handler, **kwargs)
2022-11-01 12:09:22,812 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "D:\Program Files\Ultimaker Cura 5.2.1\share\uranium\plugins\LocalFileOutputDevice\LocalFileOutputDevice.py", line 148, in requestWrite
2022-11-01 12:09:22,813 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.writeStarted.emit(self)
2022-11-01 12:09:22,813 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:22,814 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:22,814 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:22,815 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:22,815 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 361, in __performEmit
2022-11-01 12:09:22,816 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     signal.emit(*args, **kwargs)
2022-11-01 12:09:22,816 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2022-11-01 12:09:22,817 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2022-11-01 12:09:22,817 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2022-11-01 12:09:22,818 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2022-11-01 12:09:22,818 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 357, in __performEmit
2022-11-01 12:09:22,819 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     func(dest, *args, **kwargs)
2022-11-01 12:09:22,819 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Users\Kevin\AppData\Roaming\cura\5.2\plugins\AutoTowersGenerator\AutoTowersGenerator\AutoTowersGenerator.py", line 583, in _postProcess
2022-11-01 12:09:22,820 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     if self._gcodeProcessedMarker not in gcode[0]:
2022-11-01 12:09:22,820 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: IndexError: list index out of range
2022-11-01 12:09:23,325 - INFO - [MainThread] SliceInfoPlugin.SliceInfo._onRequestFinished [295]: SliceInfo sent successfully
```

**Comment by kartchnb** [comment]
Great catch! I've never tried saving to a project file before, so I never would have caught this.

It turns out to be an easy fix... I assume. I mean, I've made the error go away, but it makes me worried that there's more going on when a project is saved than I'm aware of. I'll have to look into this some more.

But, for now, I believe I have a fix. When you get a moment, would you mind trying version 2.4.1 that I just released? You can find it here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.4.1

Just download the .curaproject file that matches your Cura version and drag and drop it onto Cura's window to install it.

I appreciate you taking the time to submit an issue. I can't tell you how much it helps.

**Comment by kvnper** [comment]
Awesome, it's working now.

And I appreciate you taking your time to create this plugin, a bug report is the least I can do

**Comment by kartchnb** [comment]
That's all I needed!
